services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    env_file:
      - .env
    networks:
      - app-network

  # Optional: Remove this container if frontend is already built and copied to nginx
  # Or use it only for development builds
  frontend:
    build:
      context: ./seavphov
      dockerfile: Dockerfile
    volumes:
      - ./seavphov:/app
    command: ["sh", "-c", "npm install && npm run build"]
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./seavphov/dist:/usr/share/nginx/html
      - ./backend:/var/www/html
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
